name: Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Also trigger on release tags
  push:
    tags:
      - v[0-9]+.*

env:
  CARGO_TERM_COLOR: always
  RUSTDOCFLAGS: "--cfg docsrs -D warnings"

jobs:
  docs:
    name: Build and verify documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly  # Use nightly for all doc features
          components: rust-docs

      - name: Check documentation
        run: cargo doc --no-deps --all-features --document-private-items

      - name: Check documentation links
        run: cargo doc --no-deps --all-features --document-private-items -- -D broken_intra_doc_links

      # Only deploy docs on tag pushes
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
          force_orphan: true
          publish_branch: gh-pages
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'deploy documentation for ${{ github.ref }}'